name: Release CI

on:
  push:
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Create tag
        id: create_tag
        run: |
          TAG_NAME=$(date +"%Y.%m.%d.%H.%M")
          git tag $TAG_NAME
          git push --tags
          echo "::set-output name=tag_name::$TAG_NAME"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}